version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "auth-portal-55"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5u4n9ocaio18"
s3_prefix = "auth-portal-55"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
