export const colors = {
  background: '#000000',
  overlay: '#121212',
  buttonBackground: '#FFF',
  buttonLabel: '#000',
  title: 'rgba(255, 255, 255, 1)',
  inputBorderColor: '#FFF',
  inputBackgroundColor: '#272727',
  inputPlaceholderTextColor: '#FFF',
  inputTextColor: '#FFF',
  inputCursorColor: 'white',
  inputLabelColor: 'gray',
  error: '#FF3B30',
  loadingIndicator: '#FFF',
};
